### ISSUE TITLE
Elasticsearch not starting

### ISSUE THREAD

**Issue by smiller171** [Traackr/ansible-elasticsearch#22]
When deploying Elasticsearch with this role, Elasticsearch is not starting properly and I can find no logs. /var/logs/elasticsearch is empty. "$ sudo service elasticsearch start" says that the service has started, but then if I do a "$ sudo service elasticsearch status" it says that it is stopped.

This is my play:

    ---
    - name: deploy elasticsearch
      hosts: all
      sudo: true
      roles:
      - common
      - gpstathis.elasticsearch
      vars_files:
      - vars/elasticsearch.yaml
      - vars/main.yaml

and my vars:

    elasticsearch_cluster_name: "{{es_cluster}}"
    elasticsearch_plugin_aws_ec2_groups: "{{stack}}-elasticsearch-ASG-sg"
    elasticsearch_plugin_aws_ec2_ping_timeout: 3s
    elasticsearch_network_http_port: 9200
    elasticsearch_network_transport_tcp_port: 9300
    elasticsearch_plugin_aws_access_key: "null"
    elasticsearch_plugin_aws_secret_key: "null"
    elasticsearch_version: "{{es_version}}"
    elasticsearch_plugin_aws_version: "{{es_aws_version}}"
    elasticsearch_heap_size: 1g
    elasticsearch_max_open_files: 65535
    elasticsearch_max_locked_memory: unlimited
    elasticsearch_timezone: "America/New_York"
    elasticsearch_node_max_local_storage_nodes: 1
    elasticsearch_index_mapper_dynamic: "true"
    elasticsearch_memory_bootstrap_mlockall: "true"
    elasticsearch_gateway_type: local
    elasticsearch_gateway_recover_after_nodes: 1
    elasticsearch_gateway_recover_after_time: 1m
    elasticsearch_gateway_expected_nodes: 3
    elasticsearch_discovery_zen_minimum_master_nodes: 1
    elasticsearch_discovery_zen_ping_multicast_enabled: "false"
    
    elasticseasrch_plugins: 
    - {name: 'mobz/elasticseasrch-head'}

**Comment by smiller171** [comment]
I think I have tracked this down to Elasticsearch not starting on the right user

**Comment by smiller171** [comment]
Turns out I was passing in a heap size that was too large

**Comment by gpstathis** [comment]
@smiller171 love it when issues resolve themselves... ;-)

**Comment by smiller171** [comment]
on a tangentially related note, elasticsearch needs to fail with some verbosity. they really make it a pain to troubleshoot when they dump absolutely nothing to the logs
