### ISSUE TITLE
idempotency & Coding style

### ISSUE THREAD

**Issue by ahelal** [Traackr/ansible-elasticsearch#28]
Hi,

Thank you for sharing your code. We use it heavily. I have two suggestion.
1-  idempotency
We try to use idempotent roles only
2- Coding style
Lines are too long to read and arguments in same line make it hard.

We are working on our own fork and would like to ask would you like to have a pull request with the above ?

**Comment by ahelal** [comment]
Also versioning of roles so we can pin code ?

**Comment by gpstathis** [comment]
Pull requests are always welcome. Submit yours when you are ready and we can review together.

**Comment by ahelal** [comment]
cool https://github.com/Traackr/ansible-elasticsearch/pull/29
