### ISSUE TITLE
Wrong PID path on Debian

### ISSUE THREAD

**Issue by w4tt** [Traackr/ansible-elasticsearch#44]
while running this playbook on Debian, the PID path is wrong. it is set to `/var/run`, which will require to change permissions on `/var/run`. The Elasticsearch packages sets up `/var/run/elasticsearch/` with the correct permissions.

I've [changed it](https://github.com/w4tt/ansible-elasticsearch/commit/46ec79ab6972c8d7c9a3f2bfbbe84f69ec1709ef) in a fork, but I'm not sure it'll work on targeted distributions (I think this playbook was targeted for Ubuntu?)

**Comment by gpstathis** [comment]
@w4tt give the latest a spin. You should be able to overwrite the default PID_DIR now using the `elasticsearch_pid_dir` variable.

**Comment by w4tt** [comment]
:heart: :blue_heart: :green_heart: 

Works fine. Thanks!
