### ISSUE TITLE
yum support

### ISSUE THREAD

**Issue by davechesebrough** [Traackr/ansible-elasticsearch#49]
Need to adapt this to our RedHat-based systems - any interest in making this work across repositories? Potentially, I could abstract it to use either instead of just replacing all the apt parts.

**Comment by gpstathis** [comment]
@davechesebrough that would definitely be welcome.

**Comment by davechesebrough** [comment]
Okay - got this working today - but had to push it out the door so I gutted a lot of the apt parts. The abstraction part is not done, but the code is up on my page.

Saved me a lot of work - thanks very much.

**Comment by davechesebrough** [comment]
Closing this for now - will submit a PR if I get enough freetime
